apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: secure-prod
type: Opaque
stringData:
  # Use a much stronger password for production
  password: PROD_super_secret_#2026!
  username: prodadmin
